apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config  # myapp-config
  namespace: kube-system
data:
# key: value
  fluent.conf: |  # example fluentd configuration file
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /fluentd/log/container.log.pos
      tag kubernetes.*
      read_from_head true
      <parse>
        @type json
        time_key time
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
    </filter>

    <match kubernetes.**>
      @type stdout #or elasticsearch, kafka, etc.
    </match>