apiVersion: v1
kind: Pod
metadata:
 name: mypod
 labels:
  name: nginx
  tier: front-end
spec:
containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"    # 250 millicores (0.25 CPU cores)
        limits:
          memory: "128Mi"
          cpu: "500m"
      livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3        # health check every 3 seconds
      readinessProbe:
            httpGet:
              path: /ready
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3