apiVersion: v1
kind: Pod
metadata:
 name: my-pod
 labels:
  app: my-app
  type: nginx
  tier: front-end
spec:
containers:
    - name: nginx
      image: nginx:latest
    # ports:
    #   - containerPort: 8080  # this is optional as opposed to nodePort
      resources:
        requests:
          memory: "256Mi"  # consider resources used by k8s itself too (controller manager, apiserver, schedueler, etcd, ...)
          cpu: "500m"     # 250 millicores (0.25 CPU cores)
        limits:           # similar to cgroup ## also mitigates security risk e.g. DDOS, ...
          memory: "4096Mi"
          cpu: "4"
      livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3        # health check every 3 seconds
      readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3