apiVersion: v1 
kind: Service
metadata:
  name: mysvc
  env: test
spec:
  type: NodePort
  ports:
   - name: http
     port: 80
     targetPort: 80
     nodePort: 30004
   - name: metrics
     portt: 9090
     targetPort: 9090
     nodePort: 30005

  selector:
    app: TestApp