apiVersion: v1 
kind: Service
metadata:
  name: my-svc-clusterip
spec:
  type: ClusterIP
  selector:
    app: my-app
    type: back-end
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: metrics 
      port: 9090      # expose metrics to be collected by prometheus
      targetport: 9090 
