apiVersion: v1
kind: Service
metadata: 
  name: my-svc-loadbalancer
  labels:
    app: my-app
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080 