apiVersion: apps/v1
kind: Deployment
metadata:
  name: ayapp-deployment
  labels:
    tier: frontend
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    labels:
      tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
