apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    app: my-app
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"