apiVersion: v1 
kind: Service
metadata:
  name: my-svc-nodeport
  env: qa
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
   - name: http
     port: 80
     targetPort: 8080
     nodePort: 30004   # nodePort should be between 30000 and ~32000
   - name: metrics
     port: 9090
     targetPort: 9090
     nodePort: 30005   # nodePort should be between 30000 and ~32000